name: Setup Cloud Formation Linter with latest version
run-name: ${{ github.actor }} is checking the code with cfn-lint
on: 
  # [push]
  push:
    branches: #new commits on these branches always trigger
      - main
      - Demo_test
  pull_request:
jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scottbrenner/cfn-lint-action@v2   # dit is van github zelf gehaald: https://github.com/marketplace/actions/cfn-lint-action
        # with:
        #   command: cfn-lint -t ././templates/*.yaml # -a ../custom_rules/
      # -a for custom rules
      - run: cfn-lint --version
      - run: cfn-lint $GITHUB_WORKSPACE/templates/*.yaml -a $GITHUB_WORKSPACE/.github/customrules/cfn-lint/

      