name: Setup Cloud Formation Guard with latest version
run-name: ${{ github.actor }} is checking the code with cfn-guard
on: 
  [push]
  # push:
  #   branches: [main] #new commits on these branches always trigger
  # pull_request:
jobs:
  cloudformation-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: grolston/guard-action@main   # dit is van github zelf gehaald: https://github.com/grolston/guard-action
      #   with:
      #     data_directory: './templates/'
      #     rule_set: "cis-aws-benchmark-level-1"

      - name: Grant Execute Permissions
        run: chmod +x ./scripts/GuardScript.sh

      - name: Start CFN-Guard
        run: "./scripts/GuardScript.sh"

      - name: check version CFN-Guard
        run: "cfn-guard --version"
     
      - name: Github Action test
        run: "cfn-guard validate --data ./templates/ --rules ./.github/customrules/cfn-guard/"


      # - uses: grolston/guard-action@main
          # data_directory: '/./templates/'
          # rule_set: './customrules/cfn-guard/CustomruleTest.guard'
