name: Setup Cloud Formation Guard Action  
run-name: ${{ github.actor }} is checking the code with the premade action cfn-guard [new]
on: 
  # [push]
  push:
    branches: #new commits on these branches always trigger
      - main
      - Demo_test
  pull_request:
jobs:
  cloudformation-guard-action:
    runs-on: ubuntu-latest
    permissions:
      # only required when create-review is true
      pull-requests: write
    steps:
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: './.github/customrules/cfn-guard/'
          data: './templates/'
          create-review: true

      - name: path
        run: ls .github/customrules/cfn-guard
          
  cloudformation-guard-ruleset-action:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "JSON_FILE=rule_set_cis_aws_benchmark_level_1.json" >> $GITHUB_ENV

      - name: download ruleset
        run: '.github/customrules/DownloadRules.sh'

      - name: Validate ruleset
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: './.github/customrules/cfn-guard/downloaded_rulesets'
          data: './templates/'
          create-review: true
