name: Setup Cloud Formation Guard Action  
run-name: ${{ github.actor }} is checking the code with the premade action cfn-guard [new]
on: 
  # [push]
  push:
    branches: #new commits on these branches always trigger
      - main
      - Demo_test
  pull_request:
jobs:
  cloudformation-guard-action:
    runs-on: ubuntu-latest
    permissions:
      # only required when create-review is true
      pull-requests: write
    steps:
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: './.github/customrules/cfn-guard/'
          data: './templates/'
          create-review: true

      - name: path
        run: ls .github/customrules/
          
  # cloudformation-guard-ruleset-action:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get the latest rule set
  #       run: |
  #         # Download the rule set JSON
  #         curl -O https://raw.githubusercontent.com/aws-cloudformation/aws-guard-rules-registry/main/mappings/rule_set_cis_aws_benchmark_level_1.json

  #         # Parse the JSON and download each rule file
  #         mkdir -p downloaded_rules
  #         jq -r '.rules[].source' rule_set_cis_aws_benchmark_level_1.json | while read -r rule; do
  #           rule_url="https://raw.githubusercontent.com/aws-cloudformation/aws-guard-rules-registry/main/${rule#./}"
  #           rule_path="downloaded_rules/$(basename $rule)"
  #           curl -o $rule_path $rule_url
  #         done

      # - name: Validate ruleset
      #   uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
      #   with:
      #     rules: './.github/customrules/cfn-guard/'
      #     data: './templates/'
      #     create-review: true
