name: Setup Cloud Formation Guard Action  
run-name: ${{ github.actor }} is checking the code with the premade action cfn-guard [new]
on: 
  # [push]
  # push:
  #   branches: #new commits on these branches always trigger
  #     - main
  #     - Demo_test
  pull_request:
jobs:
  cloudformation-guard-action:
    runs-on: ubuntu-latest
    permissions:
      # only required when create-review is true
      pull-requests: write
    steps:
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
        with:
          rules: './.github/customrules/cfn-guard/'
          data: 'templates/'
          create-review: true
          
          